In [2]:
import numpy as np

In [3]:
a = np.array([1010,1000,990])
np.exp(a) / np.sum(np.exp(a))

/Users/kuesugi/Dropbox/Program/scraping/venv/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
/Users/kuesugi/Dropbox/Program/scraping/venv/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan, nan, nan])

In [4]:
c = np.max(a)
c

1010

In [5]:
a-c

array([  0, -10, -20])

In [6]:
np.exp(a-c) / np.sum(np.exp(a-c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])